name: build

on:
  workflow_dispatch:

jobs:
  build:
      name: third_party
      strategy:
        fail-fast: false
        matrix:
          config:
            - name: Windows
              os: windows-latest
              compiler: 'clang'
              compiler_cxx: 'clang'
              preparation: ''
            - name: Linux
              os: ubuntu-latest
              compiler: 'clang-18'
              compiler_cxx: 'clang++-18'
              preparation: 'sudo apt update -y && sudo apt install -y ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev'

      runs-on: ${{ matrix.config.os }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Run preparation command
          run: ${{ matrix.config.preparation }}

        - name: Apply Boost Thread Patch
          working-directory: projects/boost/libs/thread
          run: git apply ../../../../patches/boost_thread.patch

        - name: Detect MSVC
          uses: ilammy/msvc-dev-cmd@v1.13.0
          if: ${{ matrix.config.name == 'Windows' }}
          with:
            arch: x86_64

        - name: Prepare Vulkan SDK
          uses: humbletim/install-vulkan-sdk@c2aa128094d42ba02959a660f03e0a4e012192f9
          with:
            version: 1.3.275.0
            cache: true

        - name: Configure
          run: cmake -S. -B_build/_Release -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.config.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.config.compiler_cxx }}

        - name: Build
          run: cmake --build _build/_Release -j4

        - name: Install
          run: cmake --install _build/_Release

        - name: Fixup Tracy paths
          shell: bash
          run: |
            INSTALL_PREFIX="_build/_Release/install"
            CONFIG_SUBDIR="RelWithDebInfo"

            BIN_DIR="${INSTALL_PREFIX}/bin"
            LIB_DIR="${INSTALL_PREFIX}/lib"

            for BASE_DIR in "$BIN_DIR" "$LIB_DIR"; do
              SUB_DIR="${BASE_DIR}/${CONFIG_SUBDIR}"

              if [ -d "$SUB_DIR" ]; then
                for ITEM in "$SUB_DIR"/*; do
                  if [ -e "$ITEM" ]; then
                    ITEM_NAME=$(basename "$ITEM")
                    TARGET_PATH="${BASE_DIR}/${ITEM_NAME}"
                    mv -f "$ITEM" "$TARGET_PATH"
                    echo "Moved $ITEM_NAME from $SUB_DIR/ to flat $BASE_DIR"
                  fi
                done

                if [ -z "$(ls -A "$SUB_DIR")" ]; then
                  rm -rf "$SUB_DIR"
                fi
              fi
            done

        - name: Zip it up
          working-directory: _build/_Release
          run: |
            7z a psOff-3rd-${{ matrix.config.name }}.7z -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on ./install/* -xr!licenses

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: psOff-3rd-${{ matrix.config.name }}
            path: _build/_Release/psOff-3rd-${{ matrix.config.name }}.7z
